# Required
protocol: "MPSI-Sum"        # Protocol to run: MPSI / MPSI-Sum / MPSIU / MPSIU-Sum
n: 3                        # Number of participants (excluding delegate)
x0: 32768                   # Size of delegate's input set
xi: 32768                   # Size of non-delegates' input sets
i: 1024                     # Size of the intersection / intersection-with-union
b: 17                       # log_2(Size of hash map)
data_dir: "./data"          # Location of generated identifiers
result_dir: "./results"     # Location of results
l: 1024                     # Upper bound on generated associated integers (for MPSI-Sum / MPSIU-Sum)

# Optional
profile: false              # Disable profiling
